version: '3'

services:
  notebook-r:
    image: 'jupyter/r-notebook'
    ports:
      - '8117:8117'
    volumes:
      - './work:/home/sanpo/work'
    environment:
      - 'JUPYTER_PORT=8117'
      - 'NB_USER=sanpo'
      - 'CHOWN_HOME=yes'
    user: 'root'
    working_dir: '/home/sanpo/work'
    restart: 'always'

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "madison"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 9432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
